// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// p_bisec_cpp
arma::vec p_bisec_cpp(const arma::mat& theta, const arma::vec& y, const arma::mat& X, const Function& bf, int n_it);
RcppExport SEXP _pLPQR_p_bisec_cpp(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP bfSEXP, SEXP n_itSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Function& >::type bf(bfSEXP);
    Rcpp::traits::input_parameter< int >::type n_it(n_itSEXP);
    rcpp_result_gen = Rcpp::wrap(p_bisec_cpp(theta, y, X, bf, n_it));
    return rcpp_result_gen;
END_RCPP
}
// simdata_cpp
Rcpp::List simdata_cpp(const arma::mat& thetahat, const arma::mat& X, int nsub, const Function& bf, const arma::vec& index, const arma::vec& id, const arma::mat& spcor);
RcppExport SEXP _pLPQR_simdata_cpp(SEXP thetahatSEXP, SEXP XSEXP, SEXP nsubSEXP, SEXP bfSEXP, SEXP indexSEXP, SEXP idSEXP, SEXP spcorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type thetahat(thetahatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type nsub(nsubSEXP);
    Rcpp::traits::input_parameter< const Function& >::type bf(bfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type spcor(spcorSEXP);
    rcpp_result_gen = Rcpp::wrap(simdata_cpp(thetahat, X, nsub, bf, index, id, spcor));
    return rcpp_result_gen;
END_RCPP
}
// cqr
List cqr(arma::mat x, arma::vec y, arma::vec nk, arma::vec rowindex, arma::vec tau0, int nsub, int nt, arma::vec gammaint, arma::mat btau, arma::mat bderiv, int K, String type, arma::vec wt);
RcppExport SEXP _pLPQR_cqr(SEXP xSEXP, SEXP ySEXP, SEXP nkSEXP, SEXP rowindexSEXP, SEXP tau0SEXP, SEXP nsubSEXP, SEXP ntSEXP, SEXP gammaintSEXP, SEXP btauSEXP, SEXP bderivSEXP, SEXP KSEXP, SEXP typeSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rowindex(rowindexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< int >::type nsub(nsubSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gammaint(gammaintSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type btau(btauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bderiv(bderivSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(cqr(x, y, nk, rowindex, tau0, nsub, nt, gammaint, btau, bderiv, K, type, wt));
    return rcpp_result_gen;
END_RCPP
}
// cqr_adlasso
Rcpp::List cqr_adlasso(arma::mat x, arma::vec y, arma::vec nk, arma::vec rowindex, arma::vec tau0, int nsub, int nt, arma::vec gammaint, arma::vec v, double rho, double lambda, arma::mat btau, arma::mat bderiv, int K, String type, arma::vec wt);
RcppExport SEXP _pLPQR_cqr_adlasso(SEXP xSEXP, SEXP ySEXP, SEXP nkSEXP, SEXP rowindexSEXP, SEXP tau0SEXP, SEXP nsubSEXP, SEXP ntSEXP, SEXP gammaintSEXP, SEXP vSEXP, SEXP rhoSEXP, SEXP lambdaSEXP, SEXP btauSEXP, SEXP bderivSEXP, SEXP KSEXP, SEXP typeSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rowindex(rowindexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< int >::type nsub(nsubSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gammaint(gammaintSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type btau(btauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bderiv(bderivSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(cqr_adlasso(x, y, nk, rowindex, tau0, nsub, nt, gammaint, v, rho, lambda, btau, bderiv, K, type, wt));
    return rcpp_result_gen;
END_RCPP
}
// cv_cqr_adlasso0
Rcpp::List cv_cqr_adlasso0(String type, arma::vec lambda, arma::mat x, arma::vec y, arma::vec nk, arma::vec rowindex, arma::vec tau0, int nsub, int nt, arma::vec gammaint, arma::vec v, double rho, arma::mat btau, arma::mat bderiv, int K, arma::vec wt);
RcppExport SEXP _pLPQR_cv_cqr_adlasso0(SEXP typeSEXP, SEXP lambdaSEXP, SEXP xSEXP, SEXP ySEXP, SEXP nkSEXP, SEXP rowindexSEXP, SEXP tau0SEXP, SEXP nsubSEXP, SEXP ntSEXP, SEXP gammaintSEXP, SEXP vSEXP, SEXP rhoSEXP, SEXP btauSEXP, SEXP bderivSEXP, SEXP KSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rowindex(rowindexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< int >::type nsub(nsubSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gammaint(gammaintSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type btau(btauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bderiv(bderivSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(cv_cqr_adlasso0(type, lambda, x, y, nk, rowindex, tau0, nsub, nt, gammaint, v, rho, btau, bderiv, K, wt));
    return rcpp_result_gen;
END_RCPP
}
// stratumCvM_para_test_cpp
Rcpp::List stratumCvM_para_test_cpp(const Rcpp::List& data, const Rcpp::Function& bf, const Rcpp::Function& bderivf);
RcppExport SEXP _pLPQR_stratumCvM_para_test_cpp(SEXP dataSEXP, SEXP bfSEXP, SEXP bderivfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type bf(bfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type bderivf(bderivfSEXP);
    rcpp_result_gen = Rcpp::wrap(stratumCvM_para_test_cpp(data, bf, bderivf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pLPQR_p_bisec_cpp", (DL_FUNC) &_pLPQR_p_bisec_cpp, 5},
    {"_pLPQR_simdata_cpp", (DL_FUNC) &_pLPQR_simdata_cpp, 7},
    {"_pLPQR_cqr", (DL_FUNC) &_pLPQR_cqr, 13},
    {"_pLPQR_cqr_adlasso", (DL_FUNC) &_pLPQR_cqr_adlasso, 16},
    {"_pLPQR_cv_cqr_adlasso0", (DL_FUNC) &_pLPQR_cv_cqr_adlasso0, 16},
    {"_pLPQR_stratumCvM_para_test_cpp", (DL_FUNC) &_pLPQR_stratumCvM_para_test_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pLPQR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
